package by.bsuir.gameslist.ui.theme

import androidx.compose.ui.graphics.Color

val status_playing_light = Color(0xFF754ABB)
val status_planning_light = Color(0xFFE2AB08)
val status_passed_light = Color(0xFF81EA9A)
val status_abandoned_light = Color(0xFFB41919)

val status_playing_dark = Color(0xFF754ABB)
val status_planning_dark = Color(0xFFE2AB08)
val status_passed_dark = Color(0xFF81EA9A)
val status_abandoned_dark = Color(0xFFB41919)

val md_theme_light_primary = Color(0xFF8B3F96)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD6FE)
val md_theme_light_onPrimaryContainer = Color(0xFF35003F)
val md_theme_light_secondary = Color(0xFFA83259)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E0)
val md_theme_light_onSecondaryContainer = Color(0xFF3F0019)
val md_theme_light_tertiary = Color(0xFF9C4144)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD9)
val md_theme_light_onTertiaryContainer = Color(0xFF410008)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1A1D)
val md_theme_light_surfaceVariant = Color(0xFFECDFE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4D444C)
val md_theme_light_outline = Color(0xFF7E747D)
val md_theme_light_inverseOnSurface = Color(0xFFF7EEF3)
val md_theme_light_inverseSurface = Color(0xFF332F32)
val md_theme_light_inversePrimary = Color(0xFFF9ACFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8B3F96)
val md_theme_light_outlineVariant = Color(0xFFD0C3CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF9ACFF)
val md_theme_dark_onPrimary = Color(0xFF550663)
val md_theme_dark_primaryContainer = Color(0xFF70267C)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6FE)
val md_theme_dark_secondary = Color(0xFFFFB1C3)
val md_theme_dark_onSecondary = Color(0xFF66002C)
val md_theme_dark_secondaryContainer = Color(0xFF881742)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E0)
val md_theme_dark_tertiary = Color(0xFFFFB3B2)
val md_theme_dark_onTertiary = Color(0xFF5F131A)
val md_theme_dark_tertiaryContainer = Color(0xFF7E2A2E)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1A1D)
val md_theme_dark_onBackground = Color(0xFFE9E0E4)
val md_theme_dark_surface = Color(0xFF1E1A1D)
val md_theme_dark_onSurface = Color(0xFFE9E0E4)
val md_theme_dark_surfaceVariant = Color(0xFF4D444C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C3CC)
val md_theme_dark_outline = Color(0xFF998D96)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1A1D)
val md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val md_theme_dark_inversePrimary = Color(0xFF8B3F96)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF9ACFF)
val md_theme_dark_outlineVariant = Color(0xFF4D444C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF560764)